apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: federal-frog-nodejs 
  janus-idp.io/tekton: federal-frog-nodejs
  backstage.io/kubernetes-id: federal-frog-nodejs
  backstage.io/kubernetes-namespace: rhtap-e2e-ci 
  app.kubernetes.io/part-of: federal-frog-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  